### ISSUE TITLE
Fetch Openfisca YAML tests and add to Raputure DB

### ISSUE THREAD

**Issue by mischa-s** [ServiceInnovationLab/RapuTure#142]
- [x] rake task (unique key = name)
  - [x] new
  - [x] updated
  - [x] deleted
- [x] basic fetch service
- [x] Link scenarios and variables
   - [x] map over each bottom layer of YAML inputs and outputs
   - [x] check if it exists as a variable
   - [x] collect all variable ids
   - [x] add to join table variable-scenarios
- [x] change rubocop `Metrics/MethodLength` to 20
- [ ] Add rspec tests for scenarios service

**Comment by Br3nda** [comment]
Note: We will have duplicate names in open fisca -- but we shouldn't. There's an implied task here of finding incorrect and duplicate test names and fixing them in openfisca.
