### ISSUE TITLE
Install monitoring service

### ISSUE THREAD

**Issue by dlouise64** [ServiceInnovationLab/RapuTure#199]
Install Scout and RayGun

Other monitoring alternatives (some need to be looked into):
Rollbar
Sentry
Airbrake
Bugsnag
Logentries
Errlytics
TrackJS
Kafka
Atatus
Flume
Errorception

**Comment by Br3nda** [comment]
How about both? Ray gun is last resort exception/crash reporting. Scout is performance reporting
