### ISSUE TITLE
rake task - needs to remove variables

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/RapuTure#3]
"variables" are a model in the database, populated from asking OpenFisca what variables it has

The rake task that queries open fisca will create new variables, update existing variables, but it doesn't detect variables that have been removed from open fisca

A / C
 - [ ] Get rid of the ghost variables
 - [ ] It must still update the things it's updating

Notes:
If something comes back from Open Fisca and it's missing a variable, we can trust this is correct.

**Comment by mischa-s** [comment]
@Br3nda do we want a soft or hard delete?
