### ISSUE TITLE
import entities

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/RapuTure#6]

**Comment by Br3nda** [comment]
This looks like it exists but it doesn'. We show entities on the UI that are referred to by variables
Instead, we can save in a database table (from the rake task) and provide more info on them.

**Comment by mischa-s** [comment]
There was ambiguity during standup about the current state of this ticket. This code being commented out https://github.com/ServiceInnovationLab/RapuTure/blob/98df8b6371111cd7d1b939bab70cb863274c741c/lib/tasks/fetch.rake#L14 suggests maybe it is partially implemented by there are some issues? Does this jog your memory at all @Br3nda
